name: 'semantic-pull-request'
description: 'Ensure your PR title matches the Conventional Commits specification'
author: 'Kunal Nagar <knlnagar@gmail.com>'
runs:
  using: 'node12'
  main: 'dist/index.js'
